apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: vulnerable-app-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "vulnerable-app"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vulnerable-app
spec:
  hosts:
  - "*"
  gateways:
  - vulnerable-app-gateway
  http:
  - match:
    - uri:
        exact: /
    - uri:
        prefix: /static
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: vulnerable-app
        port:
          number: 9080
